# Generated by Django 3.1.7 on 2021-03-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20210317_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='e_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='e_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='e_f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='e_l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='e_m_name',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='e_m_number',
            new_name='mobile_number',
        ),
    ]
