# Generated by Django 3.1.7 on 2021-03-18 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_auto_20210317_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 3, 27, 6, 264500)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.IntegerField(max_length=13),
        ),
    ]
