# Generated by Django 3.1.7 on 2021-03-24 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_auto_20210318_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 9, 17, 10, 739709)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
