# Generated by Django 3.1.7 on 2021-03-24 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_auto_20210324_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date',
        ),
    ]
